### ISSUE TITLE
ESP-IDF Support?

### ISSUE THREAD

**Issue by homofortis** [ThingPulse/esp8266-oled-ssd1306#124]
It would be nice having this great library ported to ESP-IDF.

**Comment by juhanipaasonen** [comment]
Turns out you can already use it with ESP-IDF. It's hackish and ugly, though. Disable the warnings from project.mk, follow the instructions from https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md. Then you can, for example, take one of the demos and add a horrible
```
extern "C" void app_main();
void app_main()
{
    setup();
    while (1)
        loop();
}
```
to make it actually run.
