### ISSUE TITLE
Thanks for flooding me and all your watchers with about 112 emails from stalebot

### ISSUE THREAD

**Issue by reivaxy** [ThingPulse/esp8266-oled-ssd1306#249]

**Comment by marcelstoer** [comment]
Sorry about this Xavier. It's the unfortunate side effect of introducing stalebot into an existing repository with a history. As the bot has no control over if or to whom notifications are sent it means watchers (and maintainers) feel the pain the most.

The only way to slightly mitigate the side effect would have been to gradually increase the [days-until-stale setting](https://github.com/ThingPulse/esp8266-oled-ssd1306/blob/master/.github/stale.yml#L2) over time. Let's say to start at 500+, then 365, the 180. That way you would have received three batches of emails over time rather than all at once. I however doubt that this would have made it any better.

There will be another flood in about two weeks when the bot closes (without comment) stale issues that haven't received any updates since the last bot message.
